package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// testPCAP is the shared test pcap generated by gen_test_pcap.py
var testPCAP string

func init() {
	// Resolve testdata/test.pcap relative to the epan module root
	wd, _ := os.Getwd()
	// Try a few locations
	candidates := []string{
		filepath.Join(wd, "testdata", "test.pcap"),
		filepath.Join(wd, "..", "testdata", "test.pcap"),
		filepath.Join(wd, "..", "..", "testdata", "test.pcap"),
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			testPCAP = c
			break
		}
	}
}

func runEpanCLI(args ...string) (string, error) {
	epanBin := os.Getenv("EPAN_TEST_BIN")
	if epanBin == "" {
		epanBin = "/tmp/epan"
	}
	cmd := exec.Command(epanBin, args...)
	cmd.Stderr = nil
	out, err := cmd.Output()
	return strings.TrimSpace(string(out)), err
}

func runEpanCLIJSON(args ...string) (map[string]any, error) {
	out, err := runEpanCLI(args...)
	if err != nil {
		return nil, fmt.Errorf("epan %s: %w\noutput: %s", strings.Join(args, " "), err, out)
	}
	var result map[string]any
	if err := json.Unmarshal([]byte(out), &result); err != nil {
		return nil, fmt.Errorf("parse JSON: %w\noutput: %s", err, out)
	}
	return result, nil
}

func TestIntegration_TriageComponents(t *testing.T) {
	if testPCAP == "" {
		t.Skip("test pcap not found, run gen_test_pcap.py first")
	}

	// 1. Frame count
	t.Run("frame_count", func(t *testing.T) {
		result, err := runEpanCLIJSON("frames", "count", "--file", testPCAP)
		if err != nil {
			t.Fatal(err)
		}
		count, ok := result["count"].(float64)
		if !ok {
			t.Fatalf("count not found or wrong type: %v", result)
		}
		if count != 71 {
			t.Errorf("frame count = %v, want 71", count)
		}
		t.Logf("frame count: %v", count)
	})

	// 2. Frame count with filter
	t.Run("frame_count_filtered", func(t *testing.T) {
		result, err := runEpanCLIJSON("frames", "count", "--file", testPCAP, "--filter", "tcp")
		if err != nil {
			t.Fatal(err)
		}
		count, ok := result["count"].(float64)
		if !ok {
			t.Fatalf("count not found: %v", result)
		}
		if count <= 0 {
			t.Errorf("TCP frame count should be > 0, got %v", count)
		}
		t.Logf("TCP frame count: %v", count)
	})

	// 3. Streams
	t.Run("streams", func(t *testing.T) {
		result, err := runEpanCLIJSON("streams", "list", "--file", testPCAP)
		if err != nil {
			t.Fatal(err)
		}
		list, ok := result["list"].([]any)
		if !ok {
			t.Fatalf("streams list not found or wrong type: %v", result)
		}
		if len(list) == 0 {
			t.Error("expected at least 1 stream")
		}
		t.Logf("streams: %d", len(list))
		for i, s := range list {
			t.Logf("  stream %d: %v", i, s)
		}
	})

	// 4. Expert findings
	t.Run("expert", func(t *testing.T) {
		result, err := runEpanCLIJSON("expert", "list", "--file", testPCAP)
		if err != nil {
			t.Fatal(err)
		}
		// expert may return empty list for synthetic pcap, which is fine
		if _, ok := result["list"]; !ok {
			t.Error("expert output missing 'list' field")
		}
		t.Logf("expert: %v", result["list"])
	})

	// 5. Stats
	t.Run("stats", func(t *testing.T) {
		result, err := runEpanCLIJSON("stats", "--file", testPCAP)
		if err != nil {
			t.Fatal(err)
		}
		if _, ok := result["protocols"]; !ok {
			t.Error("stats missing 'protocols' field")
		}
		t.Logf("stats protocols: %v", result["protocols"])
	})

	// 6. Conversations
	t.Run("conversations", func(t *testing.T) {
		result, err := runEpanCLIJSON("traffic", "conversations", "list", "--file", testPCAP)
		if err != nil {
			t.Fatal(err)
		}
		list, ok := result["list"].([]any)
		if !ok {
			t.Fatalf("conversations list not found: %v", result)
		}
		if len(list) == 0 {
			t.Error("expected at least 1 conversation")
		}
		t.Logf("conversations: %d", len(list))
	})
}

func TestIntegration_Frames(t *testing.T) {
	if testPCAP == "" {
		t.Skip("test pcap not found, run gen_test_pcap.py first")
	}

	// 1. Frames page (paginated)
	t.Run("page", func(t *testing.T) {
		result, err := runEpanCLIJSON("frames", "page", "--file", testPCAP, "--page", "1", "--size", "10")
		if err != nil {
			t.Fatal(err)
		}
		list, ok := result["list"].([]any)
		if !ok {
			t.Fatalf("frames page list not found: %v", result)
		}
		if len(list) != 10 {
			t.Errorf("page 1 size 10: got %d frames, want 10", len(list))
		}
		t.Logf("page 1: %d frames", len(list))
	})

	// 2. Frames page second page
	t.Run("page2", func(t *testing.T) {
		result, err := runEpanCLIJSON("frames", "page", "--file", testPCAP, "--page", "2", "--size", "10")
		if err != nil {
			t.Fatal(err)
		}
		list, ok := result["list"].([]any)
		if !ok {
			t.Fatalf("frames page list not found: %v", result)
		}
		if len(list) != 10 {
			t.Errorf("page 2 size 10: got %d frames, want 10", len(list))
		}
		t.Logf("page 2: %d frames", len(list))
	})

	// 3. Frames page with filter
	t.Run("page_filtered", func(t *testing.T) {
		result, err := runEpanCLIJSON("frames", "page", "--file", testPCAP, "--filter", "tcp", "--page", "1", "--size", "5")
		if err != nil {
			t.Fatal(err)
		}
		list, ok := result["list"].([]any)
		if !ok {
			t.Fatalf("frames page filtered list not found: %v", result)
		}
		if len(list) == 0 {
			t.Error("expected some TCP frames")
		}
		t.Logf("filtered page: %d frames", len(list))
	})

	// 4. Get frame by number
	t.Run("get_frame", func(t *testing.T) {
		result, err := runEpanCLIJSON("frames", "get", "--file", testPCAP, "--index", "1")
		if err != nil {
			t.Fatal(err)
		}
		layers, ok := result["layers"].(map[string]any)
		if !ok {
			t.Fatalf("layers not found in get_frame output: %v", result)
		}
		frame, ok := layers["frame"].(map[string]any)
		if !ok {
			t.Fatalf("frame layer not found: %v", layers)
		}
		if _, ok := frame["frame.number"]; !ok {
			t.Error("frame missing 'frame.number' field")
		}
		t.Logf("frame 1 number: %v", frame["frame.number"])
	})

	// 5. Get frame hex
	t.Run("hex", func(t *testing.T) {
		out, err := runEpanCLI("frames", "hex", "--file", testPCAP, "--index", "1")
		if err != nil {
			t.Fatal(err)
		}
		if out == "" {
			t.Error("hex output should not be empty")
		}
		t.Logf("hex frame 1: %d chars", len(out))
	})

	// 6. Batch frames
	t.Run("batch", func(t *testing.T) {
		result, err := runEpanCLIJSON("frames", "batch", "--file", testPCAP, "--indices", "1,5,10")
		if err != nil {
			t.Fatal(err)
		}
		list, ok := result["list"].([]any)
		if !ok {
			t.Fatalf("batch list not found: %v", result)
		}
		if len(list) != 3 {
			t.Errorf("batch got %d frames, want 3", len(list))
		}
		t.Logf("batch: %d frames", len(list))
	})

	// 7. Frame fields extraction (JSONL output)
	t.Run("fields", func(t *testing.T) {
		out, err := runEpanCLI("frames", "fields", "--file", testPCAP, "--fields", "frame.number,ip.src,ip.dst")
		if err != nil {
			t.Fatal(err)
		}
		lines := strings.Split(strings.TrimSpace(out), "\n")
		if len(lines) == 0 {
			t.Error("fields extraction should return data")
		}
		t.Logf("fields: %d rows", len(lines))
		// Parse first line as JSON
		var firstRow map[string]any
		if err := json.Unmarshal([]byte(lines[0]), &firstRow); err != nil {
			t.Fatalf("first line not valid JSON: %v", err)
		}
		for k, v := range firstRow {
			t.Logf("  field %s: %v", k, v)
		}
	})
}

func TestIntegration_Follow(t *testing.T) {
	if testPCAP == "" {
		t.Skip("test pcap not found, run gen_test_pcap.py first")
	}

	// Follow TCP stream 0
	t.Run("follow_tcp_stream_0", func(t *testing.T) {
		result, err := runEpanCLIJSON("follow", "--file", testPCAP, "--protocol", "tcp", "--filter", "tcp.stream eq 0")
		if err != nil {
			t.Fatal(err)
		}
		if _, ok := result["payloads"]; !ok {
			t.Error("follow output missing 'payloads' field")
		}
		t.Logf("follow stream 0: %v", result["stream_id"])
	})
}

func TestIntegration_Filter(t *testing.T) {
	t.Run("validate", func(t *testing.T) {
		result, err := runEpanCLIJSON("filter", "validate", "--expr", "tcp.port == 80")
		if err != nil {
			t.Fatal(err)
		}
		valid, ok := result["valid"].(bool)
		if !ok {
			t.Fatalf("valid field not found: %v", result)
		}
		if !valid {
			t.Error("tcp.port == 80 should be valid")
		}
		t.Logf("filter valid: %v", valid)
	})

	t.Run("validate_invalid", func(t *testing.T) {
		result, err := runEpanCLIJSON("filter", "validate", "--expr", "invalid.field == 1")
		if err != nil {
			t.Fatal(err)
		}
		valid, ok := result["valid"].(bool)
		if !ok {
			t.Fatalf("valid field not found: %v", result)
		}
		if valid {
			t.Error("invalid.field should be invalid")
		}
		t.Logf("filter valid: %v", valid)
	})

	t.Run("validate_detailed", func(t *testing.T) {
		result, err := runEpanCLIJSON("filter", "validate-detailed", "--expr", "tcp.port == 80")
		if err != nil {
			t.Fatal(err)
		}
		t.Logf("validate-detailed: %v", result)
	})

	t.Run("suggest", func(t *testing.T) {
		result, err := runEpanCLIJSON("filter", "suggest", "--prefix", "tcp.", "--limit", "10")
		if err != nil {
			t.Fatal(err)
		}
		list, ok := result["fields"].([]any)
		if !ok {
			t.Fatalf("fields not found in suggest: %v", result)
		}
		if len(list) == 0 {
			t.Error("tcp. should have suggestions")
		}
		t.Logf("suggestions for 'tcp.': %d", len(list))
	})
}

func TestIntegration_Metadata(t *testing.T) {
	t.Run("protocols", func(t *testing.T) {
		result, err := runEpanCLIJSON("metadata", "protocols")
		if err != nil {
			t.Fatal(err)
		}
		protocols, ok := result["protocols"].([]any)
		if !ok {
			t.Fatalf("protocols not found: %v", result)
		}
		if len(protocols) == 0 {
			t.Error("protocols list should not be empty")
		}
		t.Logf("protocols: %d", len(protocols))
	})

	t.Run("field_info", func(t *testing.T) {
		result, err := runEpanCLIJSON("metadata", "field", "--name", "tcp.stream")
		if err != nil {
			t.Fatal(err)
		}
		if _, ok := result["name"]; !ok {
			t.Error("field info missing 'name'")
		}
		t.Logf("tcp.stream: %v", result["name"])
	})
}

func TestIntegration_Slice(t *testing.T) {
	if testPCAP == "" {
		t.Skip("test pcap not found, run gen_test_pcap.py first")
	}

	outFile := filepath.Join(t.TempDir(), "slice.pcap")

	t.Run("slice_by_filter", func(t *testing.T) {
		result, err := runEpanCLIJSON("slice", "pcap", "--file", testPCAP, "--filter", "frame.number <= 10", "--out", outFile)
		if err != nil {
			t.Fatal(err)
		}
		t.Logf("slice result: %v", result)

		// Verify the output file exists
		if _, err := os.Stat(outFile); os.IsNotExist(err) {
			t.Error("slice output file not created")
		} else {
			t.Logf("slice output: %s exists", outFile)
		}
	})

	t.Run("slice_by_indices", func(t *testing.T) {
		outFile2 := filepath.Join(t.TempDir(), "slice2.pcap")
		result, err := runEpanCLIJSON("slice", "pcap", "--file", testPCAP, "--indices", "1,3,5,7", "--out", outFile2)
		if err != nil {
			t.Fatal(err)
		}
		t.Logf("slice by indices: %v", result)
		if _, err := os.Stat(outFile2); os.IsNotExist(err) {
			t.Error("slice by indices output file not created")
		}
	})
}

func TestIntegration_Evidence(t *testing.T) {
	if testPCAP == "" {
		t.Skip("test pcap not found, run gen_test_pcap.py first")
	}

	t.Run("evidence_bundle", func(t *testing.T) {
		result, err := runEpanCLIJSON("evidence", "bundle", "--file", testPCAP)
		if err != nil {
			// Evidence bundle may fail on synthetic pcap, that's acceptable
			t.Logf("evidence bundle error (may be expected): %v", err)
			return
		}
		t.Logf("evidence bundle: %v", result)
	})
}

func TestIntegration_Tap(t *testing.T) {
	if testPCAP == "" {
		t.Skip("test pcap not found, run gen_test_pcap.py first")
	}

	t.Run("tap_endpoints", func(t *testing.T) {
		result, err := runEpanCLIJSON("tap", "endpoints", "--file", testPCAP, "--type", "ip")
		if err != nil {
			t.Fatal(err)
		}
		list, ok := result["list"].([]any)
		if !ok {
			t.Fatalf("endpoints list not found: %v", result)
		}
		if len(list) == 0 {
			t.Error("expected at least 1 endpoint")
		}
		t.Logf("endpoints: %d", len(list))
	})
}

func TestIntegration_Stats(t *testing.T) {
	if testPCAP == "" {
		t.Skip("test pcap not found, run gen_test_pcap.py first")
	}

	t.Run("stats_summary", func(t *testing.T) {
		result, err := runEpanCLIJSON("stats", "--file", testPCAP)
		if err != nil {
			t.Fatal(err)
		}
		if _, ok := result["protocols"]; !ok {
			t.Error("stats missing 'protocols' field")
		}
		t.Logf("stats: %v", result["protocols"])
	})
}

func TestIntegration_Extract(t *testing.T) {
	if testPCAP == "" {
		t.Skip("test pcap not found, run gen_test_pcap.py first")
	}

	outDir := filepath.Join(t.TempDir(), "extracted")

	t.Run("extract_files", func(t *testing.T) {
		result, err := runEpanCLIJSON("extract", "--file", testPCAP, "--out", outDir)
		if err != nil {
			// Extract may fail on synthetic pcap with no real files, acceptable
			t.Logf("extract error (may be expected): %v", err)
			return
		}
		t.Logf("extract: %v", result)
	})
}

func TestIntegration_Version(t *testing.T) {
	out, err := runEpanCLI("version")
	if err != nil {
		t.Fatal(err)
	}
	var result map[string]any
	if err := json.Unmarshal([]byte(out), &result); err != nil {
		t.Fatalf("version output not valid JSON: %v", err)
	}
	if _, ok := result["version"]; !ok {
		t.Error("version output missing 'version' field")
	}
	t.Logf("version: %v", result["version"])
}